version: "3"
services:
  backend:
    build:
      context: .
      dockerfile: docker/backend.dockerfile
    env_file: ./server/.env
    volumes:
      - "./scatlaslc/scatlaslc.db:/data/scatlaslc.db:ro"
    ports:
      - "9000:9000"
  frontend:
    build:
      context: .
      dockerfile: docker/frontend.dockerfile
    environment:
      API_HOST: http://backend:9000
    links:
      - backend:backend
    ports:
      - "3000:80"
